#!/bin/sh

docker run \
         -it \
         --rm \
         --network overviewserver_default \
         -e 'POLL_URL=http://overview-worker:9032/Email' \
         $(docker build --target=dev -q .) \
         "$@"
